apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: dev
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: sumon737/nodeapp:{{BUILD_NUMBER}}
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: dev
spec:
  selector:
    app: nodeapp 
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp-ingress
  namespace: dev
  labels:
    app: nodeapp
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: nodeapp.sumon.com
      http:
        paths:
          - backend:
              service:
                name: nodeapp-service
                port:
                  number: 80
            path: /
            pathType: Exact
